Feature/ PDF handler
ems-project/EMSSubmissionBundle pull request #20
Opened 2020-03-18 10:04 UTC by coppee

2020-03-18 10:10 UTC, Davidmattei submitted a review, later dismissed
Great!

2020-03-18 12:58 UTC, dameert requested changes

2020-03-18 12:58 UTC, dameert commented on Handler/PdfHandler.php
> +            dd($stream);
@Davidmattei you accepted this! :p

2020-03-18 12:58 UTC, dameert commented on Handler/PdfHandler.php
> +final class PdfHandler extends AbstractHandler
```suggestion
final class PdfCreateHandler extends AbstractHandler
```

2020-03-18 12:58 UTC, dameert commented on Handler/PdfHandler.php
> +final class PdfHandler extends AbstractHandler
A second handler is needed for the use case "save on sftp server" --> SftpStorageHandler

2020-03-18 12:58 UTC, dameert commented on Handler/PdfHandler.php
> +final class PdfHandler extends AbstractHandler
SftpStorageHandler requires that previousResponse is not null, and implements a new interface to indicate that we have a "saveable" file.

2020-06-12 12:18 UTC, Davidmattei commented
Closed added in version 2.0 https://github.com/ems-project/EMSSubmissionBundle/pull/31

2020-06-12 12:18 UTC, closed without merging